# Generated by Django 4.0.6 on 2022-07-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=255)),
                ('upload_image', models.FileField(upload_to='upload_image')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('blood', models.CharField(max_length=20)),
                ('mobail_no', models.IntegerField()),
                ('passport_number', models.CharField(max_length=200)),
                ('visa', models.CharField(max_length=255)),
                ('emirates', models.CharField(max_length=255)),
                ('passport_expiry', models.DateField()),
                ('visa_expiry', models.DateField()),
                ('emirates_expiry', models.DateField()),
                ('insurence', models.CharField(max_length=255)),
                ('insurence_expiry', models.DateField()),
                ('insurance_copy', models.FileField(upload_to='insurance_copy')),
                ('passport_copy', models.FileField(upload_to='passport_copy')),
                ('visa_copy', models.FileField(upload_to='visa_copy')),
                ('emirates_copy', models.FileField(upload_to='emirates_copy')),
                ('other_document', models.FileField(upload_to='other_document')),
                ('notification_email', models.EmailField(max_length=254)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branch')),
                ('catogory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.company')),
            ],
        ),
    ]
