# Generated by Django 4.0.6 on 2022-07-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_employee_dob_alter_employee_emirates_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobail_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
